# Dependabot configuration file to automate dependency updates
# These checks run on the 2nd day of each month at 09:00 AM Bucharest time

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend/"
    schedule:
      interval: "cron"
      cronjob: "0 9 2 * *"
      timezone: "Europe/Bucharest"

  - package-ecosystem: "uv"
    directory: "/backend/"
    schedule:
      interval: "cron"
      cronjob: "0 9 2 * *"
      timezone: "Europe/Bucharest"

  - package-ecosystem: "docker"
    directory: "/docker/dockerfiles/"
    schedule:
      interval: "cron"
      cronjob: "0 9 2 * *"
      timezone: "Europe/Bucharest"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "cron"
      cronjob: "0 9 2 * *"
      timezone: "Europe/Bucharest"
