name: Frontend Check

on:
  push:
    branches:
      - "*"
      - "main"
    paths:
      - "backend/assets/**"
      - "backend/static_extras/**"
      - "backend/templates/**"
      - "backend/package*.json"
      - "backend/.nvmrc"
      - "backend/postcss.config.js"
      - "backend/vite.config.js"
      - "Dockerfile*"
      - "docker-compose*.yml"
      - ".github/workflows/frontend_check.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/assets/**"
      - "backend/static_extras/**"
      - "backend/templates/**"
      - "backend/package*.json"
      - "backend/.nvmrc"
      - "backend/postcss.config.js"
      - "backend/vite.config.js"
      - "Dockerfile*"
      - "docker-compose*.yml"
      - ".github/workflows/frontend_check.yml"

jobs:

  npm_prod:
    name: Run `npm run build` in production mode for Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Set-up Node.js environment
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"
          node-version-file: "backend/.nvmrc"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          npm ci

      - name: Build frontend
        working-directory: ./backend
        run: |
          npm run build
